[tox]
env_list = py311,py312,py313,py314,lint

[testenv]
basepython =
    py311: python3.11
    py312: python3.12
    py313: python3.13
    py314: python3.14

description = run the tests with pytest
package = wheel
wheel_build_env = .pkg
commands =
    python -m unittest discover -s tests -v

[testenv:lint]
basepython = 
    lint: python3.11
deps =
    mypy
    flake8
    types-requests
    types-icalendar
commands = 
    flake8 src/caldav2ntfy
    mypy src/caldav2ntfy
